[tox]
envlist = py39, py310, py311, py312, py313
# Since you are testing scripts and not building a library yourself
no_package = true 

[testenv]
deps = 
    # This tells tox to install everything inside your requirements file
    -r requirements.txt
    # We still need pytest to actually run the tests
    pytest
commands = 
    pytest testsuite/tests/