# Generated by Django 5.2.3 on 2025-06-26 22:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAPIKey',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('_key_encrypted', models.TextField(db_column='key')),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vectorx_version', models.CharField(default='0.33.1', help_text='Version of VectorX used for this test run', max_length=50)),
                ('test_type', models.IntegerField(choices=[(1, 'Create Index'), (2, 'Upsert Vectors'), (3, 'Query Index'), (4, 'Delete Vectors & Delete Index'), (5, 'End-to-End Pipeline')])),
                ('pipeline_mode', models.BooleanField(default=False)),
                ('report', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending - Waiting to start'), ('running', 'Running - Currently executing'), ('success', 'Success - All tests passed'), ('partial', 'Partial - Some tests failed'), ('failed', 'Failed - All tests failed')], default='pending', max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, help_text='The user who triggered this test run', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('api_key_reference', models.ForeignKey(blank=True, help_text='Reference to the API key used', null=True, on_delete=django.db.models.deletion.SET_NULL, to='testsuite.userapikey')),
            ],
        ),
    ]
