# Generated by Django 5.2.3 on 2025-07-10 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsuite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testrun',
            name='platform',
            field=models.CharField(blank=True, choices=[('linux', 'Linux'), ('windows', 'Windows'), ('macos', 'macOS')], help_text='The platform (OS) where this test was executed', max_length=10, null=True),
        ),
    ]
