# Generated by Django 5.2.3 on 2025-07-15 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsuite', '0002_testrun_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testrun',
            name='platform',
            field=models.CharField(blank=True, choices=[('linux', 'Linux Only'), ('windows', 'Windows Only'), ('linux_windows', 'Run on Linux & Windows')], help_text='The platform (OS) where this test was executed', max_length=15, null=True),
        ),
    ]
