# Generated by Django 5.2.3 on 2025-07-16 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsuite', '0003_alter_testrun_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testrun',
            name='test_type',
            field=models.IntegerField(choices=[(1, 'Test Python vecx Client'), (2, 'Test Hybrid Index'), (3, 'Test VectorX LangChain Integration'), (4, 'Test VectorX LlamaIndex Integration'), (5, 'Test VectorX Crew AI Integration')]),
        ),
    ]
