# Generated by Django 5.2.3 on 2025-07-17 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsuite', '0004_alter_testrun_test_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testrun',
            name='test_type',
            field=models.IntegerField(choices=[(1, 'Python vecx Client'), (2, 'Hybrid Index'), (3, 'VectorX LangChain Integration'), (4, 'VectorX LlamaIndex Integration'), (5, 'VectorX Crew AI Integration')]),
        ),
        migrations.AlterField(
            model_name='testrun',
            name='vectorx_version',
            field=models.CharField(default='0.33.1b2', help_text='Version of VectorX used for this test run', max_length=50),
        ),
    ]
