# Generated by Django 5.2.4 on 2025-07-24 09:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsuite', '0005_alter_testrun_test_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='testrun',
            name='vectorx_version',
            field=models.CharField(default='0.33.1b3', help_text='Version of VectorX used for this test run', max_length=50),
        ),
        migrations.CreateModel(
            name='LibraryUpdateRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('library', models.CharField(max_length=100)),
                ('current_version', models.CharField(help_text='The current version of the library', max_length=50)),
                ('update_version', models.CharField(help_text='The version for which library has to be updated', max_length=50)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='running', max_length=10)),
                ('message', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
