# Generated by Django 5.2.4 on 2025-07-28 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsuite', '0006_alter_testrun_vectorx_version_libraryupdaterequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testrun',
            name='vectorx_version',
            field=models.CharField(help_text='Version of VectorX used for this test run', max_length=50),
        ),
    ]
